# Generated by Django 5.0.2 on 2024-03-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercredential",
            name="client_id",
            field=models.CharField(max_length=128),
        ),
    ]
