# Generated by Django 5.0.2 on 2024-03-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_created_user_modified_usercredential_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendar_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
