# Generated by Django 5.0.2 on 2024-02-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="ref",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
