# Generated by Django 5.0.2 on 2024-02-29 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_team_ref"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("championship", "home_team", "away_team", "start_at")},
        ),
    ]
